#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTN.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLdienthoai")]
	public partial class dbQLdienthoaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertChitietdonhang(Chitietdonhang instance);
    partial void UpdateChitietdonhang(Chitietdonhang instance);
    partial void DeleteChitietdonhang(Chitietdonhang instance);
    partial void InsertDonhang(Donhang instance);
    partial void UpdateDonhang(Donhang instance);
    partial void DeleteDonhang(Donhang instance);
    partial void InsertHangsanxuat(Hangsanxuat instance);
    partial void UpdateHangsanxuat(Hangsanxuat instance);
    partial void DeleteHangsanxuat(Hangsanxuat instance);
    partial void InsertHedieuhanh(Hedieuhanh instance);
    partial void UpdateHedieuhanh(Hedieuhanh instance);
    partial void DeleteHedieuhanh(Hedieuhanh instance);
    partial void InsertNguoidung(Nguoidung instance);
    partial void UpdateNguoidung(Nguoidung instance);
    partial void DeleteNguoidung(Nguoidung instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    partial void InsertSanpham(Sanpham instance);
    partial void UpdateSanpham(Sanpham instance);
    partial void DeleteSanpham(Sanpham instance);
    #endregion
		
		public dbQLdienthoaiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLdienthoaiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLdienthoaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLdienthoaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLdienthoaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLdienthoaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this.GetTable<Chitietdonhang>();
			}
		}
		
		public System.Data.Linq.Table<Donhang> Donhangs
		{
			get
			{
				return this.GetTable<Donhang>();
			}
		}
		
		public System.Data.Linq.Table<Hangsanxuat> Hangsanxuats
		{
			get
			{
				return this.GetTable<Hangsanxuat>();
			}
		}
		
		public System.Data.Linq.Table<Hedieuhanh> Hedieuhanhs
		{
			get
			{
				return this.GetTable<Hedieuhanh>();
			}
		}
		
		public System.Data.Linq.Table<Nguoidung> Nguoidungs
		{
			get
			{
				return this.GetTable<Nguoidung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<Sanpham> Sanphams
		{
			get
			{
				return this.GetTable<Sanpham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _PassAdmin;
		
		private string _HoTen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassAdminChanging(string value);
    partial void OnPassAdminChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PassAdmin
		{
			get
			{
				return this._PassAdmin;
			}
			set
			{
				if ((this._PassAdmin != value))
				{
					this.OnPassAdminChanging(value);
					this.SendPropertyChanging();
					this._PassAdmin = value;
					this.SendPropertyChanged("PassAdmin");
					this.OnPassAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chitietdonhang")]
	public partial class Chitietdonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madon;
		
		private int _Masp;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _Dongia;
		
		private EntityRef<Donhang> _Donhang;
		
		private EntityRef<Sanpham> _Sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadonChanging(int value);
    partial void OnMadonChanged();
    partial void OnMaspChanging(int value);
    partial void OnMaspChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(System.Nullable<decimal> value);
    partial void OnDongiaChanged();
    #endregion
		
		public Chitietdonhang()
		{
			this._Donhang = default(EntityRef<Donhang>);
			this._Sanpham = default(EntityRef<Sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Madon
		{
			get
			{
				return this._Madon;
			}
			set
			{
				if ((this._Madon != value))
				{
					if (this._Donhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadonChanging(value);
					this.SendPropertyChanging();
					this._Madon = value;
					this.SendPropertyChanged("Madon");
					this.OnMadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Masp
		{
			get
			{
				return this._Masp;
			}
			set
			{
				if ((this._Masp != value))
				{
					if (this._Sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaspChanging(value);
					this.SendPropertyChanging();
					this._Masp = value;
					this.SendPropertyChanged("Masp");
					this.OnMaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Donhang_Chitietdonhang", Storage="_Donhang", ThisKey="Madon", OtherKey="Madon", IsForeignKey=true)]
		public Donhang Donhang
		{
			get
			{
				return this._Donhang.Entity;
			}
			set
			{
				Donhang previousValue = this._Donhang.Entity;
				if (((previousValue != value) 
							|| (this._Donhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Donhang.Entity = null;
						previousValue.Chitietdonhangs.Remove(this);
					}
					this._Donhang.Entity = value;
					if ((value != null))
					{
						value.Chitietdonhangs.Add(this);
						this._Madon = value.Madon;
					}
					else
					{
						this._Madon = default(int);
					}
					this.SendPropertyChanged("Donhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanpham_Chitietdonhang", Storage="_Sanpham", ThisKey="Masp", OtherKey="Masp", IsForeignKey=true)]
		public Sanpham Sanpham
		{
			get
			{
				return this._Sanpham.Entity;
			}
			set
			{
				Sanpham previousValue = this._Sanpham.Entity;
				if (((previousValue != value) 
							|| (this._Sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sanpham.Entity = null;
						previousValue.Chitietdonhangs.Remove(this);
					}
					this._Sanpham.Entity = value;
					if ((value != null))
					{
						value.Chitietdonhangs.Add(this);
						this._Masp = value.Masp;
					}
					else
					{
						this._Masp = default(int);
					}
					this.SendPropertyChanged("Sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Donhang")]
	public partial class Donhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Madon;
		
		private System.Nullable<bool> _Datthanhtoan;
		
		private System.Nullable<bool> _Tinhtrang;
		
		private System.Nullable<System.DateTime> _Ngaydat;
		
		private System.Nullable<System.DateTime> _Ngaygiao;
		
		private System.Nullable<int> _MaNguoidung;
		
		private EntitySet<Chitietdonhang> _Chitietdonhangs;
		
		private EntityRef<Nguoidung> _Nguoidung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMadonChanging(int value);
    partial void OnMadonChanged();
    partial void OnDatthanhtoanChanging(System.Nullable<bool> value);
    partial void OnDatthanhtoanChanged();
    partial void OnTinhtrangChanging(System.Nullable<bool> value);
    partial void OnTinhtrangChanged();
    partial void OnNgaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydatChanged();
    partial void OnNgaygiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaygiaoChanged();
    partial void OnMaNguoidungChanging(System.Nullable<int> value);
    partial void OnMaNguoidungChanged();
    #endregion
		
		public Donhang()
		{
			this._Chitietdonhangs = new EntitySet<Chitietdonhang>(new Action<Chitietdonhang>(this.attach_Chitietdonhangs), new Action<Chitietdonhang>(this.detach_Chitietdonhangs));
			this._Nguoidung = default(EntityRef<Nguoidung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Madon
		{
			get
			{
				return this._Madon;
			}
			set
			{
				if ((this._Madon != value))
				{
					this.OnMadonChanging(value);
					this.SendPropertyChanging();
					this._Madon = value;
					this.SendPropertyChanged("Madon");
					this.OnMadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datthanhtoan", DbType="Bit")]
		public System.Nullable<bool> Datthanhtoan
		{
			get
			{
				return this._Datthanhtoan;
			}
			set
			{
				if ((this._Datthanhtoan != value))
				{
					this.OnDatthanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Datthanhtoan = value;
					this.SendPropertyChanged("Datthanhtoan");
					this.OnDatthanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="Bit")]
		public System.Nullable<bool> Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydat
		{
			get
			{
				return this._Ngaydat;
			}
			set
			{
				if ((this._Ngaydat != value))
				{
					this.OnNgaydatChanging(value);
					this.SendPropertyChanging();
					this._Ngaydat = value;
					this.SendPropertyChanged("Ngaydat");
					this.OnNgaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiao", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaygiao
		{
			get
			{
				return this._Ngaygiao;
			}
			set
			{
				if ((this._Ngaygiao != value))
				{
					this.OnNgaygiaoChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiao = value;
					this.SendPropertyChanged("Ngaygiao");
					this.OnNgaygiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoidung", DbType="Int")]
		public System.Nullable<int> MaNguoidung
		{
			get
			{
				return this._MaNguoidung;
			}
			set
			{
				if ((this._MaNguoidung != value))
				{
					if (this._Nguoidung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoidungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoidung = value;
					this.SendPropertyChanged("MaNguoidung");
					this.OnMaNguoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Donhang_Chitietdonhang", Storage="_Chitietdonhangs", ThisKey="Madon", OtherKey="Madon")]
		public EntitySet<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this._Chitietdonhangs;
			}
			set
			{
				this._Chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoidung_Donhang", Storage="_Nguoidung", ThisKey="MaNguoidung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public Nguoidung Nguoidung
		{
			get
			{
				return this._Nguoidung.Entity;
			}
			set
			{
				Nguoidung previousValue = this._Nguoidung.Entity;
				if (((previousValue != value) 
							|| (this._Nguoidung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nguoidung.Entity = null;
						previousValue.Donhangs.Remove(this);
					}
					this._Nguoidung.Entity = value;
					if ((value != null))
					{
						value.Donhangs.Add(this);
						this._MaNguoidung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoidung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nguoidung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Donhang = this;
		}
		
		private void detach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Donhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hangsanxuat")]
	public partial class Hangsanxuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mahang;
		
		private string _Tenhang;
		
		private EntitySet<Sanpham> _Sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahangChanging(int value);
    partial void OnMahangChanged();
    partial void OnTenhangChanging(string value);
    partial void OnTenhangChanged();
    #endregion
		
		public Hangsanxuat()
		{
			this._Sanphams = new EntitySet<Sanpham>(new Action<Sanpham>(this.attach_Sanphams), new Action<Sanpham>(this.detach_Sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhang", DbType="NChar(10)")]
		public string Tenhang
		{
			get
			{
				return this._Tenhang;
			}
			set
			{
				if ((this._Tenhang != value))
				{
					this.OnTenhangChanging(value);
					this.SendPropertyChanging();
					this._Tenhang = value;
					this.SendPropertyChanged("Tenhang");
					this.OnTenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hangsanxuat_Sanpham", Storage="_Sanphams", ThisKey="Mahang", OtherKey="Mahang")]
		public EntitySet<Sanpham> Sanphams
		{
			get
			{
				return this._Sanphams;
			}
			set
			{
				this._Sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Hangsanxuat = this;
		}
		
		private void detach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Hangsanxuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hedieuhanh")]
	public partial class Hedieuhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mahdh;
		
		private string _Tenhdh;
		
		private EntitySet<Sanpham> _Sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahdhChanging(int value);
    partial void OnMahdhChanged();
    partial void OnTenhdhChanging(string value);
    partial void OnTenhdhChanged();
    #endregion
		
		public Hedieuhanh()
		{
			this._Sanphams = new EntitySet<Sanpham>(new Action<Sanpham>(this.attach_Sanphams), new Action<Sanpham>(this.detach_Sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahdh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mahdh
		{
			get
			{
				return this._Mahdh;
			}
			set
			{
				if ((this._Mahdh != value))
				{
					this.OnMahdhChanging(value);
					this.SendPropertyChanging();
					this._Mahdh = value;
					this.SendPropertyChanged("Mahdh");
					this.OnMahdhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhdh", DbType="NChar(10)")]
		public string Tenhdh
		{
			get
			{
				return this._Tenhdh;
			}
			set
			{
				if ((this._Tenhdh != value))
				{
					this.OnTenhdhChanging(value);
					this.SendPropertyChanging();
					this._Tenhdh = value;
					this.SendPropertyChanged("Tenhdh");
					this.OnTenhdhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hedieuhanh_Sanpham", Storage="_Sanphams", ThisKey="Mahdh", OtherKey="Mahdh")]
		public EntitySet<Sanpham> Sanphams
		{
			get
			{
				return this._Sanphams;
			}
			set
			{
				this._Sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Hedieuhanh = this;
		}
		
		private void detach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Hedieuhanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nguoidung")]
	public partial class Nguoidung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiDung;
		
		private string _Hoten;
		
		private string _Email;
		
		private string _Dienthoai;
		
		private string _Matkhau;
		
		private System.Nullable<int> _IDQuyen;
		
		private string _Diachi;
		
		private EntitySet<Donhang> _Donhangs;
		
		private EntityRef<PhanQuyen> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(int value);
    partial void OnMaNguoiDungChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDienthoaiChanging(string value);
    partial void OnDienthoaiChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnIDQuyenChanging(System.Nullable<int> value);
    partial void OnIDQuyenChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    #endregion
		
		public Nguoidung()
		{
			this._Donhangs = new EntitySet<Donhang>(new Action<Donhang>(this.attach_Donhangs), new Action<Donhang>(this.detach_Donhangs));
			this._PhanQuyen = default(EntityRef<PhanQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dienthoai", DbType="NChar(10)")]
		public string Dienthoai
		{
			get
			{
				return this._Dienthoai;
			}
			set
			{
				if ((this._Dienthoai != value))
				{
					this.OnDienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Dienthoai = value;
					this.SendPropertyChanged("Dienthoai");
					this.OnDienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="Int")]
		public System.Nullable<int> IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					if (this._PhanQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoidung_Donhang", Storage="_Donhangs", ThisKey="MaNguoiDung", OtherKey="MaNguoidung")]
		public EntitySet<Donhang> Donhangs
		{
			get
			{
				return this._Donhangs;
			}
			set
			{
				this._Donhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_Nguoidung", Storage="_PhanQuyen", ThisKey="IDQuyen", OtherKey="IDQuyen", IsForeignKey=true)]
		public PhanQuyen PhanQuyen
		{
			get
			{
				return this._PhanQuyen.Entity;
			}
			set
			{
				PhanQuyen previousValue = this._PhanQuyen.Entity;
				if (((previousValue != value) 
							|| (this._PhanQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanQuyen.Entity = null;
						previousValue.Nguoidungs.Remove(this);
					}
					this._PhanQuyen.Entity = value;
					if ((value != null))
					{
						value.Nguoidungs.Add(this);
						this._IDQuyen = value.IDQuyen;
					}
					else
					{
						this._IDQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Donhangs(Donhang entity)
		{
			this.SendPropertyChanging();
			entity.Nguoidung = this;
		}
		
		private void detach_Donhangs(Donhang entity)
		{
			this.SendPropertyChanging();
			entity.Nguoidung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDQuyen;
		
		private string _TenQuyen;
		
		private EntitySet<Nguoidung> _Nguoidungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDQuyenChanging(int value);
    partial void OnIDQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._Nguoidungs = new EntitySet<Nguoidung>(new Action<Nguoidung>(this.attach_Nguoidungs), new Action<Nguoidung>(this.detach_Nguoidungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(20)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanQuyen_Nguoidung", Storage="_Nguoidungs", ThisKey="IDQuyen", OtherKey="IDQuyen")]
		public EntitySet<Nguoidung> Nguoidungs
		{
			get
			{
				return this._Nguoidungs;
			}
			set
			{
				this._Nguoidungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Nguoidungs(Nguoidung entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = this;
		}
		
		private void detach_Nguoidungs(Nguoidung entity)
		{
			this.SendPropertyChanging();
			entity.PhanQuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanpham")]
	public partial class Sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Masp;
		
		private string _Tensp;
		
		private System.Nullable<decimal> _Giatien;
		
		private System.Nullable<int> _Soluong;
		
		private string _Mota;
		
		private System.Nullable<int> _Thesim;
		
		private System.Nullable<int> _Bonhotrong;
		
		private System.Nullable<bool> _Sanphammoi;
		
		private System.Nullable<int> _Ram;
		
		private string _Anhbia;
		
		private System.Nullable<int> _Mahang;
		
		private System.Nullable<int> _Mahdh;
		
		private EntitySet<Chitietdonhang> _Chitietdonhangs;
		
		private EntityRef<Hangsanxuat> _Hangsanxuat;
		
		private EntityRef<Hedieuhanh> _Hedieuhanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaspChanging(int value);
    partial void OnMaspChanged();
    partial void OnTenspChanging(string value);
    partial void OnTenspChanged();
    partial void OnGiatienChanging(System.Nullable<decimal> value);
    partial void OnGiatienChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnThesimChanging(System.Nullable<int> value);
    partial void OnThesimChanged();
    partial void OnBonhotrongChanging(System.Nullable<int> value);
    partial void OnBonhotrongChanged();
    partial void OnSanphammoiChanging(System.Nullable<bool> value);
    partial void OnSanphammoiChanged();
    partial void OnRamChanging(System.Nullable<int> value);
    partial void OnRamChanged();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    partial void OnMahangChanging(System.Nullable<int> value);
    partial void OnMahangChanged();
    partial void OnMahdhChanging(System.Nullable<int> value);
    partial void OnMahdhChanged();
    #endregion
		
		public Sanpham()
		{
			this._Chitietdonhangs = new EntitySet<Chitietdonhang>(new Action<Chitietdonhang>(this.attach_Chitietdonhangs), new Action<Chitietdonhang>(this.detach_Chitietdonhangs));
			this._Hangsanxuat = default(EntityRef<Hangsanxuat>);
			this._Hedieuhanh = default(EntityRef<Hedieuhanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Masp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Masp
		{
			get
			{
				return this._Masp;
			}
			set
			{
				if ((this._Masp != value))
				{
					this.OnMaspChanging(value);
					this.SendPropertyChanging();
					this._Masp = value;
					this.SendPropertyChanged("Masp");
					this.OnMaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensp", DbType="NVarChar(50)")]
		public string Tensp
		{
			get
			{
				return this._Tensp;
			}
			set
			{
				if ((this._Tensp != value))
				{
					this.OnTenspChanging(value);
					this.SendPropertyChanging();
					this._Tensp = value;
					this.SendPropertyChanged("Tensp");
					this.OnTenspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giatien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giatien
		{
			get
			{
				return this._Giatien;
			}
			set
			{
				if ((this._Giatien != value))
				{
					this.OnGiatienChanging(value);
					this.SendPropertyChanging();
					this._Giatien = value;
					this.SendPropertyChanged("Giatien");
					this.OnGiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thesim", DbType="Int")]
		public System.Nullable<int> Thesim
		{
			get
			{
				return this._Thesim;
			}
			set
			{
				if ((this._Thesim != value))
				{
					this.OnThesimChanging(value);
					this.SendPropertyChanging();
					this._Thesim = value;
					this.SendPropertyChanged("Thesim");
					this.OnThesimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonhotrong", DbType="Int")]
		public System.Nullable<int> Bonhotrong
		{
			get
			{
				return this._Bonhotrong;
			}
			set
			{
				if ((this._Bonhotrong != value))
				{
					this.OnBonhotrongChanging(value);
					this.SendPropertyChanging();
					this._Bonhotrong = value;
					this.SendPropertyChanged("Bonhotrong");
					this.OnBonhotrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sanphammoi", DbType="Bit")]
		public System.Nullable<bool> Sanphammoi
		{
			get
			{
				return this._Sanphammoi;
			}
			set
			{
				if ((this._Sanphammoi != value))
				{
					this.OnSanphammoiChanging(value);
					this.SendPropertyChanging();
					this._Sanphammoi = value;
					this.SendPropertyChanged("Sanphammoi");
					this.OnSanphammoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ram", DbType="Int")]
		public System.Nullable<int> Ram
		{
			get
			{
				return this._Ram;
			}
			set
			{
				if ((this._Ram != value))
				{
					this.OnRamChanging(value);
					this.SendPropertyChanging();
					this._Ram = value;
					this.SendPropertyChanged("Ram");
					this.OnRamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="NVarChar(10)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahang", DbType="Int")]
		public System.Nullable<int> Mahang
		{
			get
			{
				return this._Mahang;
			}
			set
			{
				if ((this._Mahang != value))
				{
					if (this._Hangsanxuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahangChanging(value);
					this.SendPropertyChanging();
					this._Mahang = value;
					this.SendPropertyChanged("Mahang");
					this.OnMahangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahdh", DbType="Int")]
		public System.Nullable<int> Mahdh
		{
			get
			{
				return this._Mahdh;
			}
			set
			{
				if ((this._Mahdh != value))
				{
					if (this._Hedieuhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahdhChanging(value);
					this.SendPropertyChanging();
					this._Mahdh = value;
					this.SendPropertyChanged("Mahdh");
					this.OnMahdhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanpham_Chitietdonhang", Storage="_Chitietdonhangs", ThisKey="Masp", OtherKey="Masp")]
		public EntitySet<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this._Chitietdonhangs;
			}
			set
			{
				this._Chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hangsanxuat_Sanpham", Storage="_Hangsanxuat", ThisKey="Mahang", OtherKey="Mahang", IsForeignKey=true)]
		public Hangsanxuat Hangsanxuat
		{
			get
			{
				return this._Hangsanxuat.Entity;
			}
			set
			{
				Hangsanxuat previousValue = this._Hangsanxuat.Entity;
				if (((previousValue != value) 
							|| (this._Hangsanxuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hangsanxuat.Entity = null;
						previousValue.Sanphams.Remove(this);
					}
					this._Hangsanxuat.Entity = value;
					if ((value != null))
					{
						value.Sanphams.Add(this);
						this._Mahang = value.Mahang;
					}
					else
					{
						this._Mahang = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hangsanxuat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hedieuhanh_Sanpham", Storage="_Hedieuhanh", ThisKey="Mahdh", OtherKey="Mahdh", IsForeignKey=true)]
		public Hedieuhanh Hedieuhanh
		{
			get
			{
				return this._Hedieuhanh.Entity;
			}
			set
			{
				Hedieuhanh previousValue = this._Hedieuhanh.Entity;
				if (((previousValue != value) 
							|| (this._Hedieuhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hedieuhanh.Entity = null;
						previousValue.Sanphams.Remove(this);
					}
					this._Hedieuhanh.Entity = value;
					if ((value != null))
					{
						value.Sanphams.Add(this);
						this._Mahdh = value.Mahdh;
					}
					else
					{
						this._Mahdh = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hedieuhanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Sanpham = this;
		}
		
		private void detach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Sanpham = null;
		}
	}
}
#pragma warning restore 1591
